project_id = "taskme-local"

[db]
port = 54322
shadow_port = 54320
major_version = 17

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600

